services:
  keycloak:
    build:
      context: ./quarkus/container
      dockerfile: Dockerfile
      args:
        KEYCLOAK_DIST: ./keycloak-999.0.0-SNAPSHOT.tar.gz
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    platform: linux/amd64
    environment:
      KC_DB: postgres
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HTTPS_ENABLED: false
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./themes:/opt/keycloak/themes:ro
      - ./providers:/opt/keycloak/providers:ro
    networks:
      - keycloak-network

  # Maven ビルド用サービス
  maven-builder:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    working_dir: /app
    profiles:
      - tools
    networks:
      - keycloak-network

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local
  maven_cache:
    driver: local

networks:
  keycloak-network:
    driver: bridge
