name: "Deploy Keycloak"
description: "Build and deploy Keycloak to AWS"

inputs:
  environment:
    description: "Target environment (stg or prd)"
    required: true
  aws_role_arn:
    description: "AWS IAM Role ARN for deployment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: ./.github/actions/build-keycloak
      with:
        upload-m2-repo: false
        upload-dist: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ inputs.aws_role_arn }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Docker Build and Deploy Keycloak
      shell: bash
      run: |
        make deploy ENVIRONMENT=${{ inputs.environment }}

    - name: Logout of Amazon ECR
      if: always()
      shell: bash
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
